export const DISCORD_INVITE = "https://discord.gg/kVqaRA6aqM";
export const RANK_POWER = {F:1,E:2,D:3,C:4,B:5,A:6,S:7,SS:8,SSS:9};
export function rankValue(rank='F'){return RANK_POWER[String(rank).toUpperCase().replace('RANK ','')] || 0}
export function normalizeUser(id,u={}){return {id,name:u.username||u.name||u.displayName||u.discordName||`Adventurer ${id.slice(-4)}`,rank:u.rank||u.questRank||'F',spina:Number(u.spina||u.gold||u.coins||u.balance||0),questClear:Number(u.questClear||u.questsCleared||u.completedQuests||u.clear||0),exp:Number(u.exp||u.xp||0)}}
export async function loadUsers(){try{const {initializeApp}=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js');const {getDatabase,ref,onValue}=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js');const {firebaseConfig}=await import('./firebase-config.js');const app=initializeApp(firebaseConfig);const db=getDatabase(app);return new Promise((resolve)=>{onValue(ref(db,'users'),snap=>{const raw=snap.val()||{};resolve(Object.entries(raw).map(([id,u])=>normalizeUser(id,u)))},{onlyOnce:true});});}catch(e){console.warn(e);return []}}
export function setActive(){const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('[data-nav]').forEach(a=>{if(a.getAttribute('href')===path)a.classList.add('active')});document.querySelectorAll('[data-discord]').forEach(a=>a.href=DISCORD_INVITE)}
export function renderRows(el,users,type='quest',limit=5){const sorters={quest:(a,b)=>b.questClear-a.questClear,tier:(a,b)=>rankValue(b.rank)-rankValue(a.rank)||b.exp-a.exp,spina:(a,b)=>b.spina-a.spina};const labels={quest:u=>`${u.questClear} clear`,tier:u=>`Rank ${u.rank}`,spina:u=>`${u.spina.toLocaleString('id-ID')} Spina`};const sorted=[...users].sort(sorters[type]).slice(0,limit);el.innerHTML=sorted.length?sorted.map((u,i)=>`<div class="rankRow"><div class="pos">${i+1}</div><div><div class="name">${escapeHtml(u.name)}</div><div class="meta">Rank ${escapeHtml(u.rank)} • ${u.exp.toLocaleString('id-ID')} EXP</div></div><div class="score">${labels[type](u)}</div></div>`).join(''):`<div class="empty">Belum ada data user dari Firebase.</div>`}
export function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
setActive();
